### ISSUE TITLE
See status of current package

### ISSUE THREAD

**Issue by hussani** [filhodanuvem/Phartitura#3]
I think would be cool if can view the status of the package that i seeing.

Follow examples below.

Seeing any package currently:

> `<package name>` `<version>`
> `<package description>`
> Dependencies
> `<dependency name>` `<dependency rule>` `[...]` `<dependency status>`
> `<dependency name>` `<dependency rule>` `[...]` `<dependency status>`
> [...]

Propose when see a package:

> `<package name>` `<version>` _**`<package status>`**_
> `<package description>`
> Dependencies
> `<dependency name>` `<dependency rule>` `[...]` `<dependency status>`
> `<dependency name>` `<dependency rule>` `[...]` `<dependency status>`
> [...]

If i see the status of the current package i can know if is alternative to my project or not.

What you think about it?

**Comment by filhodanuvem** [comment]
It's a great idea @hussani !
Phartitura is inspired by [David-www](https://david-dm.org/bower/bower), I would like have a route like phartitura.com/symfony/symfony.png that shows a image/status of project. 

I will try it soon, or if you want do it yourself, that would be amazing. 

Thanks for your feedback.
:cloud: :smile:

**Comment by filhodanuvem** [comment]
It's done :metal:  http://phartitura.com/Guzzle/Http

**Comment by hussani** [comment]
Nice!!!
